name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make 
      run: make platform=windows
    - uses: actions/upload-artifact@v3
     with:
      name: Build-Windows
      path: build
